version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_linux:
    docker:
      - image: beauby/faiss-circleci:cpu
    environment:
      OMP_NUM_THREADS: 10
      MKL_THREADING_LAYER: GNU
    steps:
      - checkout
      - run:
          name: Build faiss library
          command: |
            cmake -B build -DBUILD_TESTING=ON -DFAISS_ENABLE_GPU=OFF \
                  -DCMAKE_BUILD_TYPE=Release -DBLA_VENDOR=Intel10_64_dyn .
            make -C build -j faiss
      - run:
          name: Test faiss library
          command: |
            make -C build -j faiss_test
            make -C build test
      - run:
          name: Build python extension
          command: |
            make -C build -j swigfaiss
            cd build/faiss/python
            python3 setup.py build
      - run:
          name: Test python extension
          command: |
            export PYTHONPATH="$(ls -d ./build/faiss/python/build/lib*/)"
            python3 -m unittest discover ./tests

  build_osx:
    macos:
      xcode: 11.6.0
    environment:
      OMP_NUM_THREADS: 10
    steps:
      - checkout
      - run:
          name: Install Homebrew packages
          command: |
            brew install cmake swig libomp
      - run:
          name: Install numpy/scipy
          command: |
            pip3 install numpy scipy
      - run:
          name: Generate Makefiles
          command: |
            cmake -B build -DBUILD_TESTING=ON -DFAISS_ENABLE_GPU=OFF \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DPython_EXECUTABLE=/usr/local/bin/python3 .
      - run:
          name: Build faiss library
          command: |
            make -C build -j faiss
      - run:
          name: Test faiss library
          command: |
            make -C build -j faiss_test
            make -C build test
      - run:
          name: Build python extension
          command: |
            make -C build -j swigfaiss
            cd build/faiss/python
            python3 setup.py build
      - run:
          name: Test python extension
          command: |
            PYTHONPATH="$(ls -d ./build/faiss/python/build/lib*/)" python3 -m unittest discover ./tests

  build_windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Build/test
          command: |
            conda install conda-build
            cd conda
            conda build faiss --python 3.7

  build_linux_gpu:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build/test
          command: |
            docker build -t faiss -f .circleci/Dockerfile.faiss_gpu .
            docker run --gpus all faiss make -C build test

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_linux_gpu:
          requires:
            - build_linux
      - build_osx
      - build_windows
